06/24/2025 01:19:28 PM :: PartTracker :: DEBUG    :: --------------------------------------------------------------
06/24/2025 01:19:28 PM :: PartTracker :: DEBUG    :: Beginning particle tracking for h329-11
06/24/2025 01:19:28 PM :: PartTracker :: DEBUG    :: Getting stored filepaths and haloids
06/24/2025 01:19:28 PM :: PartTracker :: ERROR    :: Uncaught exception
Traceback (most recent call last):
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/particletracking.py", line 257, in <module>
    filepaths, haloids, h1ids = get_stored_filepaths_haloids(sim,z0haloid)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/base.py", line 106, in get_stored_filepaths_haloids
    haloids = d['haloids'][sim][z0haloid]
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 11
06/24/2025 01:23:48 PM :: PartTracker :: DEBUG    :: --------------------------------------------------------------
06/24/2025 01:23:48 PM :: PartTracker :: DEBUG    :: Beginning particle tracking for h329-11
06/24/2025 01:23:48 PM :: PartTracker :: DEBUG    :: Getting stored filepaths and haloids
06/24/2025 01:23:48 PM :: PartTracker :: ERROR    :: Uncaught exception
Traceback (most recent call last):
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/particletracking.py", line 257, in <module>
    filepaths, haloids, h1ids = get_stored_filepaths_haloids(sim,z0haloid)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/base.py", line 106, in get_stored_filepaths_haloids
    haloids = d['haloids'][sim][z0haloid]
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 11
06/24/2025 01:24:29 PM :: PartTracker :: DEBUG    :: --------------------------------------------------------------
06/24/2025 01:24:29 PM :: PartTracker :: DEBUG    :: Beginning particle tracking for h329-11
06/24/2025 01:24:29 PM :: PartTracker :: DEBUG    :: Getting stored filepaths and haloids
06/24/2025 01:24:29 PM :: PartTracker :: ERROR    :: Uncaught exception
Traceback (most recent call last):
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/particletracking.py", line 257, in <module>
    filepaths, haloids, h1ids = get_stored_filepaths_haloids(sim,z0haloid)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/base.py", line 106, in get_stored_filepaths_haloids
    haloids = d['haloids'][sim][z0haloid]
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 11
06/24/2025 01:24:57 PM :: PartTracker :: DEBUG    :: --------------------------------------------------------------
06/24/2025 01:24:57 PM :: PartTracker :: DEBUG    :: Beginning particle tracking for h329-11
06/24/2025 01:24:57 PM :: PartTracker :: DEBUG    :: Getting stored filepaths and haloids
06/24/2025 01:24:57 PM :: PartTracker :: ERROR    :: Uncaught exception
Traceback (most recent call last):
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/particletracking.py", line 257, in <module>
    filepaths, haloids, h1ids = get_stored_filepaths_haloids(sim,z0haloid)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/base.py", line 106, in get_stored_filepaths_haloids
    print(f'haloids: {haloids}\nh1ids: {h1ids}')
                      ^^^^^^^
UnboundLocalError: cannot access local variable 'haloids' where it is not associated with a value
06/24/2025 01:25:07 PM :: PartTracker :: DEBUG    :: --------------------------------------------------------------
06/24/2025 01:25:07 PM :: PartTracker :: DEBUG    :: Beginning particle tracking for h329-11
06/24/2025 01:25:07 PM :: PartTracker :: DEBUG    :: Getting stored filepaths and haloids
06/24/2025 01:25:07 PM :: PartTracker :: ERROR    :: Uncaught exception
Traceback (most recent call last):
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/particletracking.py", line 257, in <module>
    filepaths, haloids, h1ids = get_stored_filepaths_haloids(sim,z0haloid)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sackmann/Documents/MAP/akins/Justice_League_Code/Analysis/RamPressure/base.py", line 106, in get_stored_filepaths_haloids
    print(f'haloids: {haloids}\nh1ids: {h1ids}')
                      ^^^^^^^
UnboundLocalError: cannot access local variable 'haloids' where it is not associated with a value
